### ISSUE TITLE
No preferences windows on Linux mint 17.2

### ISSUE THREAD

**Issue by PhillipMwaniki** [qdore/Mutate#104]
I have issues setting up the default key since I am not able to bring up the mutate settings window. I keep getting an error that mutate is running each time I click on the icon from menu. A default hotkey setting on the documentation would really help out here

**Comment by benfalk** [comment]
Try this:
First make sure mutate is not running with `pkill mutate`
Then find and edit `~/.config/Mutate/config.ini`

You will want to find the section that looks like this:

```
[default]
ScriptAddress=
IconAddress=
HotKey=Ctrl+y
Argument=none
Height=0.3
```

This is what I have in mine and it has the HotKey set to ctrl + y,  I would try something like this first to see if you can get mutate running with some simple hotkey first.  Also I have my height set to .3 because on multiple displays of different shapes it will get lost.  You may also want to play with the Height: it goes between .1 to .9
