### ISSUE TITLE
Why do Mutate deb package depend fcitx?

### ISSUE THREAD

**Issue by MakeNowJust** [qdore/Mutate#49]
Hi.

`mutate` package depends `fcitx-libs-qt5` and it recommends `fcitx` accordingly.  In addition to, default behavior of Ubuntu `apt-get` is to install recommend package, so `apt-get install mutate` installs `fcitx` despite our wants.  (Of course, `--no-install-recommends` works effectively in this case.)

We have a ourselves's favorite IME framework (i.e. fcitx, ibus, uim...) for we don't want to install other IME frameworks.

Is `fcitx-libs-qt5` true dependence for `mutate`?  Can you reduce it from dependences?

(See #34. You reduce it, dependences size reduce too.)

- - -

BTW,

https://github.com/qdore/Mutate/blob/0a09a0b1b6514658b6dcad75b1ca0f2c6eb2e2a2/debian/mutate/DEBIAN/postinst#L47-L61

```bash
fcitx="True"
for i in `cat /etc/profile`;do                                            
if [ "$i" = "QT5_IM_MODULE=fcitx" ];then
fcitx="False"
fi
done
if [ "$fcitx" = "True" ];then
echo "export QT_IM_MODULE=fcitx" >> /etc/profile
echo "export QT5_IM_MODULE=fcitx" >> /etc/profile
echo "export XIM_PROGRAM=fcitx" >> /etc/profile
echo "export XIM=fcitx" >> /etc/profile
echo "export GTK_IM_MODULE=fcitx" >> /etc/profile
echo "export QT_IM_MODULE=fcitx" >> /etc/profile
echo 'export XMODIFIERS="@im=fcitx"' >> /etc/profile
fi
```

Many many many many many people do NOT want this behavior.

Why?  Such a behavior should include library's installer.  If you want this behavior, you should asks to the forum <https://bugs.launchpad.net/ubuntu>.  Please don't make our `/etc/profile` dirty!

I'm waiting your good reply :laughing:

**Comment by Blackrush** [comment]
:+1: :+1: :+1:

**Comment by Velmont** [comment]
Hmm.  It's even weird so many "-dev" packages are needed.  Quite simply zero of those should be needed.  I think the Debian package is very wrong.

Ohh!  Reading the package, it is indeed very weirdly done.  It's using qmake and make so that it can run "make install" at the end.  This is not how packaging should be done.  Everything should be provided in the correct folder from the start, not exploded from the postinstall like it's currently done.

I think it's best not to use this package at all. It will mess up the system more than just doing a manual install of make install. :)

**Comment by codeThatThinks** [comment]
Hey, wait a sec, fcitx isn't actually used anywhere in the code. It's only a dep because qdore uses it for input on his machine and thought to include it as a dep.

From what the ArchWiki says, users who want to use fcitx as an input method only need to install fcitx-qt5 (probably different package on other distros) and fcitx will work in _any_ qt5 program. So I'll remove it.

**Comment by MakeNowJust** [comment]
Thanks @codeThatThinks and Good job :smile:

**Comment by santigarcor** [comment]
I think this problem isn't solved, when i want to install it from the ppa, it says that it needs fcitx package
